// Auto-generated from Figma design tokens export. Do not edit by hand.
export interface ColorToken { category: string; name: string; cssVar: string }

export const colorTokens: ColorToken[] = [
  { category: "Canvas", name: "Canvas/Default", cssVar: "--canvas-default" },
  { category: "Fill", name: "Fill/Neutral/Primary", cssVar: "--fill-neutral-primary" },
  { category: "Fill", name: "Fill/Neutral/Secondary", cssVar: "--fill-neutral-secondary" },
  { category: "Fill", name: "Fill/Neutral/Tertiary", cssVar: "--fill-neutral-tertiary" },
  { category: "Fill", name: "Fill/Neutral/Hover/Primary", cssVar: "--fill-neutral-hover-primary" },
  { category: "Fill", name: "Fill/Neutral/Hover/Secondary", cssVar: "--fill-neutral-hover-secondary" },
  { category: "Fill", name: "Fill/Neutral/Hover/Tertiary", cssVar: "--fill-neutral-hover-tertiary" },
  { category: "Fill", name: "Fill/Neutral/Pressed/Primary", cssVar: "--fill-neutral-pressed-primary" },
  { category: "Fill", name: "Fill/Neutral Inverse/Primary", cssVar: "--fill-neutral-inverse-primary" },
  { category: "Fill", name: "Fill/Neutral Inverse/Secondary", cssVar: "--fill-neutral-inverse-secondary" },
  { category: "Fill", name: "Fill/Neutral/Pressed/Secondary", cssVar: "--fill-neutral-pressed-secondary" },
  { category: "Fill", name: "Fill/Neutral Inverse/Hover/Primary", cssVar: "--fill-neutral-inverse-hover-primary" },
  { category: "Fill", name: "Fill/Neutral Inverse/Hover/Secondary", cssVar: "--fill-neutral-inverse-hover-secondary" },
  { category: "Fill", name: "Fill/Neutral/Pressed/Tertiary", cssVar: "--fill-neutral-pressed-tertiary" },
  { category: "Fill", name: "Fill/Neutral Inverse/Pressed/Primary", cssVar: "--fill-neutral-inverse-pressed-primary" },
  { category: "Fill", name: "Fill/Neutral Inverse/Pressed/Secondary", cssVar: "--fill-neutral-inverse-pressed-secondary" },
  { category: "Fill", name: "Fill/Accent1/Primary", cssVar: "--fill-accent1-primary" },
  { category: "Fill", name: "Fill/Accent1/Secondary", cssVar: "--fill-accent1-secondary" },
  { category: "Fill", name: "Fill/Accent1/Tertiary", cssVar: "--fill-accent1-tertiary" },
  { category: "Fill", name: "Fill/Accent1/Hover/Primary", cssVar: "--fill-accent1-hover-primary" },
  { category: "Fill", name: "Fill/Accent1/Hover/Secondary", cssVar: "--fill-accent1-hover-secondary" },
  { category: "Fill", name: "Fill/Accent1/Hover/Tertiary", cssVar: "--fill-accent1-hover-tertiary" },
  { category: "Fill", name: "Fill/Accent1/Pressed/Primary", cssVar: "--fill-accent1-pressed-primary" },
  { category: "Fill", name: "Fill/Accent1/Pressed/Secondary", cssVar: "--fill-accent1-pressed-secondary" },
  { category: "Fill", name: "Fill/Accent1/Pressed/Tertiary", cssVar: "--fill-accent1-pressed-tertiary" },
  { category: "Fill", name: "Fill/Accent2/Primary", cssVar: "--fill-accent2-primary" },
  { category: "Fill", name: "Fill/Accent2/Secondary", cssVar: "--fill-accent2-secondary" },
  { category: "Fill", name: "Fill/Accent2/Tertiary", cssVar: "--fill-accent2-tertiary" },
  { category: "Fill", name: "Fill/Accent3/Primary", cssVar: "--fill-accent3-primary" },
  { category: "Fill", name: "Fill/Accent3/Secondary", cssVar: "--fill-accent3-secondary" },
  { category: "Fill", name: "Fill/Accent3/Tertiary", cssVar: "--fill-accent3-tertiary" },
  { category: "Fill", name: "Fill/Accent3/Hover/Primary", cssVar: "--fill-accent3-hover-primary" },
  { category: "Fill", name: "Fill/Accent3/Hover/Secondary", cssVar: "--fill-accent3-hover-secondary" },
  { category: "Fill", name: "Fill/Accent3/Hover/Tertiary", cssVar: "--fill-accent3-hover-tertiary" },
  { category: "Fill", name: "Fill/Accent3/Pressed/Primary", cssVar: "--fill-accent3-pressed-primary" },
  { category: "Fill", name: "Fill/Accent3/Pressed/Secondary", cssVar: "--fill-accent3-pressed-secondary" },
  { category: "Fill", name: "Fill/Accent3/Pressed/Tertiary", cssVar: "--fill-accent3-pressed-tertiary" },
  { category: "Fill", name: "Fill/Negative/Primary", cssVar: "--fill-negative-primary" },
  { category: "Fill", name: "Fill/Warning/Primary", cssVar: "--fill-warning-primary" },
  { category: "Fill", name: "Fill/Negative/Secondary", cssVar: "--fill-negative-secondary" },
  { category: "Fill", name: "Fill/Negative/Tertiary", cssVar: "--fill-negative-tertiary" },
  { category: "Fill", name: "Fill/Neutral/Transparent/Primary", cssVar: "--fill-neutral-transparent-primary" },
  { category: "Fill", name: "Fill/Neutral/Transparent/Secondary", cssVar: "--fill-neutral-transparent-secondary" },
  { category: "Fill", name: "Fill/Neutral/Transparent/Tertiary", cssVar: "--fill-neutral-transparent-tertiary" },
  { category: "Fill", name: "Fill/Accent2/Hover/Primary", cssVar: "--fill-accent2-hover-primary" },
  { category: "Fill", name: "Fill/Accent2/Hover/Secondary", cssVar: "--fill-accent2-hover-secondary" },
  { category: "Fill", name: "Fill/Accent2/Hover/Tertiary", cssVar: "--fill-accent2-hover-tertiary" },
  { category: "Fill", name: "Fill/Accent2/Pressed/Primary", cssVar: "--fill-accent2-pressed-primary" },
  { category: "Fill", name: "Fill/Accent2/Pressed/Secondary", cssVar: "--fill-accent2-pressed-secondary" },
  { category: "Fill", name: "Fill/Accent2/Pressed/Tertiary", cssVar: "--fill-accent2-pressed-tertiary" },
  { category: "Stroke", name: "Stroke/Default/Primary", cssVar: "--stroke-default-primary" },
  { category: "Stroke", name: "Stroke/Default/Secondary", cssVar: "--stroke-default-secondary" },
  { category: "Stroke", name: "Stroke/Default/Tertiary", cssVar: "--stroke-default-tertiary" },
  { category: "Stroke", name: "Stroke/Default/Primary Low", cssVar: "--stroke-default-primary-low" },
  { category: "Fill", name: "Fill/Warning/Secondary", cssVar: "--fill-warning-secondary" },
  { category: "Fill", name: "Fill/Warning/Tertiary", cssVar: "--fill-warning-tertiary" },
  { category: "Stroke", name: "Stroke/Negative/Primary", cssVar: "--stroke-negative-primary" },
  { category: "Stroke", name: "Stroke/Negative/Secondary", cssVar: "--stroke-negative-secondary" },
  { category: "Stroke", name: "Stroke/Negative/Tertiary", cssVar: "--stroke-negative-tertiary" },
  { category: "Text", name: "Text/Neutral/Primary", cssVar: "--text-neutral-primary" },
  { category: "Text", name: "Text/Neutral/Secondary", cssVar: "--text-neutral-secondary" },
  { category: "Text", name: "Text/Neutral/Tertiary", cssVar: "--text-neutral-tertiary" },
  { category: "Text", name: "Text/Neutral/Secondary High", cssVar: "--text-neutral-secondary-high" },
  { category: "Text", name: "Text/Inverse/Primary", cssVar: "--text-inverse-primary" },
  { category: "Text", name: "Text/Inverse/Secondary", cssVar: "--text-inverse-secondary" },
  { category: "Text", name: "Text/Accent1/Primary", cssVar: "--text-accent1-primary" },
  { category: "Text", name: "Text/Accent1/Secondary", cssVar: "--text-accent1-secondary" },
  { category: "Text", name: "Text/Accent1/Tertiary", cssVar: "--text-accent1-tertiary" },
  { category: "Text", name: "Text/Positive/Primary", cssVar: "--text-positive-primary" },
  { category: "Text", name: "Text/Positive/Secondary", cssVar: "--text-positive-secondary" },
  { category: "Text", name: "Text/Positive/Tertiary", cssVar: "--text-positive-tertiary" },
  { category: "Text", name: "Text/Negative/Primary", cssVar: "--text-negative-primary" },
  { category: "Text", name: "Text/Negative/Secondary", cssVar: "--text-negative-secondary" },
  { category: "Text", name: "Text/Negative/Tertiary", cssVar: "--text-negative-tertiary" },
  { category: "Text", name: "Text/Accent2/Primary", cssVar: "--text-accent2-primary" },
  { category: "Text", name: "Text/Accent 3/Primary", cssVar: "--text-accent-3-primary" },
  { category: "Text", name: "Text/Accent2/Secondary", cssVar: "--text-accent2-secondary" },
  { category: "Icon", name: "Icon/Default/Primary", cssVar: "--icon-default-primary" },
  { category: "Text", name: "Text/Accent2/Tertiary", cssVar: "--text-accent2-tertiary" },
  { category: "Icon", name: "Icon/Default/Secondary High", cssVar: "--icon-default-secondary-high" },
  { category: "Icon", name: "Icon/Default/Secondary", cssVar: "--icon-default-secondary" },
  { category: "Icon", name: "Icon/Default/Tertiary", cssVar: "--icon-default-tertiary" },
  { category: "Icon", name: "Icon/Positive/Primary", cssVar: "--icon-positive-primary" },
  { category: "Icon", name: "Icon/Positive/Secondary", cssVar: "--icon-positive-secondary" },
  { category: "Icon", name: "Icon/Positive/Tertiary", cssVar: "--icon-positive-tertiary" },
  { category: "Icon", name: "Icon/Negative/Primary", cssVar: "--icon-negative-primary" },
  { category: "Icon", name: "Icon/Accent1/Primary", cssVar: "--icon-accent1-primary" },
  { category: "Icon", name: "Icon/Accent2/Primary", cssVar: "--icon-accent2-primary" },
  { category: "Icon", name: "Icon/Accent1/Secondary", cssVar: "--icon-accent1-secondary" },
  { category: "Icon", name: "Icon/Accent2/Secondary", cssVar: "--icon-accent2-secondary" },
  { category: "Icon", name: "Icon/Accent 3/Primary", cssVar: "--icon-accent-3-primary" },
  { category: "Icon", name: "Icon/Accent 3/Secondary", cssVar: "--icon-accent-3-secondary" },
  { category: "Icon", name: "Icon/Accent 3/Tertiary", cssVar: "--icon-accent-3-tertiary" },
  { category: "Icon", name: "Icon/Inverse/Primary", cssVar: "--icon-inverse-primary" },
  { category: "Icon", name: "Icon/Inverse/Secondary", cssVar: "--icon-inverse-secondary" },
  { category: "Icon", name: "Icon/Accent1/Tertiary", cssVar: "--icon-accent1-tertiary" },
  { category: "Stroke", name: "Stroke/Accent1/Primary", cssVar: "--stroke-accent1-primary" },
  { category: "Stroke", name: "Stroke/Accent1/Secondary", cssVar: "--stroke-accent1-secondary" },
  { category: "Stroke", name: "Stroke/Accent1/Tertiary", cssVar: "--stroke-accent1-tertiary" },
  { category: "Stroke", name: "Stroke/Accent1/Focus", cssVar: "--stroke-accent1-focus" },
  { category: "Gradient base", name: "Gradient base/Blue", cssVar: "--gradient-base-blue" },
  { category: "Gradient base", name: "Gradient base/Dark blue", cssVar: "--gradient-base-dark-blue" },
  { category: "Gradient base", name: "Gradient base/White surface 0", cssVar: "--gradient-base-white-surface-0" },
  { category: "Gradient base", name: "Gradient base/White surface 1", cssVar: "--gradient-base-white-surface-1" },
  { category: "Gradient base", name: "Gradient base/Red", cssVar: "--gradient-base-red" },
  { category: "Gradient base", name: "Gradient base/Light Green", cssVar: "--gradient-base-light-green" },
  { category: "Gradient base", name: "Gradient base/Grey stroke", cssVar: "--gradient-base-grey-stroke" },
  { category: "Gradient base", name: "Gradient base/Yellow", cssVar: "--gradient-base-yellow" },
  { category: "Scrim", name: "Scrim/Scrim Fill", cssVar: "--scrim-scrim-fill" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Pulse Green", cssVar: "--info-graphics-price-chart-pulse-green" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Green", cssVar: "--info-graphics-price-chart-green" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Red", cssVar: "--info-graphics-price-chart-red" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Pulse Red", cssVar: "--info-graphics-price-chart-pulse-red" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Tooltip line", cssVar: "--info-graphics-price-chart-tooltip-line" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Tooltip bg", cssVar: "--info-graphics-price-chart-tooltip-bg" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Pulse Blue", cssVar: "--info-graphics-price-chart-pulse-blue" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Blue", cssVar: "--info-graphics-price-chart-blue" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Pulse Purple", cssVar: "--info-graphics-price-chart-pulse-purple" },
  { category: "Info Graphics", name: "Info Graphics/Price chart/Purple", cssVar: "--info-graphics-price-chart-purple" },
  { category: "Info Graphics", name: "Info Graphics/Chart/Legend 0", cssVar: "--info-graphics-chart-legend-0" },
  { category: "Info Graphics", name: "Info Graphics/Chart/Legend 1", cssVar: "--info-graphics-chart-legend-1" },
  { category: "Info Graphics", name: "Info Graphics/Chart/Legend 2", cssVar: "--info-graphics-chart-legend-2" },
  { category: "Info Graphics", name: "Info Graphics/Chart/Legend 3", cssVar: "--info-graphics-chart-legend-3" },
  { category: "Info Graphics", name: "Info Graphics/Chart/Legend 4", cssVar: "--info-graphics-chart-legend-4" },
  { category: "Fill", name: "Fill/Negative/Hover/Primary", cssVar: "--fill-negative-hover-primary" },
  { category: "Fill", name: "Fill/Negative/Hover/Secondary", cssVar: "--fill-negative-hover-secondary" },
  { category: "Fill", name: "Fill/Negative/Hover/Tertiary", cssVar: "--fill-negative-hover-tertiary" },
  { category: "Fill", name: "Fill/Negative/Pressed/Primary", cssVar: "--fill-negative-pressed-primary" },
  { category: "Fill", name: "Fill/Negative/Pressed/Secondary", cssVar: "--fill-negative-pressed-secondary" },
  { category: "Fill", name: "Fill/Positive/Primary", cssVar: "--fill-positive-primary" },
  { category: "Fill", name: "Fill/Positive/Secondary", cssVar: "--fill-positive-secondary" },
  { category: "Fill", name: "Fill/Positive/Tertiary", cssVar: "--fill-positive-tertiary" },
  { category: "Fill", name: "Fill/Positive/Hover/Primary", cssVar: "--fill-positive-hover-primary" },
  { category: "Fill", name: "Fill/Positive/Hover/Secondary", cssVar: "--fill-positive-hover-secondary" },
  { category: "Fill", name: "Fill/Positive/Hover/Tertiary", cssVar: "--fill-positive-hover-tertiary" },
  { category: "Fill", name: "Fill/Positive/Pressed/Primary", cssVar: "--fill-positive-pressed-primary" },
  { category: "Fill", name: "Fill/Negative/Pressed/Tertiary", cssVar: "--fill-negative-pressed-tertiary" },
  { category: "Fill", name: "Fill/Positive/Pressed/Secondary", cssVar: "--fill-positive-pressed-secondary" },
  { category: "Fill", name: "Fill/Positive/Pressed/Tertiary", cssVar: "--fill-positive-pressed-tertiary" },
  { category: "Stroke", name: "Stroke/Positive/Primary", cssVar: "--stroke-positive-primary" },
  { category: "Stroke", name: "Stroke/Positive/Secondary", cssVar: "--stroke-positive-secondary" },
  { category: "Stroke", name: "Stroke/Positive/Tertiary", cssVar: "--stroke-positive-tertiary" },
  { category: "Fill", name: "Fill/Warning/Hover/Primary", cssVar: "--fill-warning-hover-primary" },
  { category: "Fill", name: "Fill/Warning/Hover/Secondary", cssVar: "--fill-warning-hover-secondary" },
  { category: "Fill", name: "Fill/Warning/Hover/Tertiary", cssVar: "--fill-warning-hover-tertiary" },
  { category: "Fill", name: "Fill/Warning/Pressed/Primary", cssVar: "--fill-warning-pressed-primary" },
  { category: "Fill", name: "Fill/Warning/Pressed/Secondary", cssVar: "--fill-warning-pressed-secondary" },
  { category: "Fill", name: "Fill/Warning/Pressed/Tertiary", cssVar: "--fill-warning-pressed-tertiary" },
  { category: "Stroke", name: "Stroke/Warning/Primary", cssVar: "--stroke-warning-primary" },
  { category: "Stroke", name: "Stroke/Warning/Secondary", cssVar: "--stroke-warning-secondary" },
  { category: "Stroke", name: "Stroke/Warning/Tertiary", cssVar: "--stroke-warning-tertiary" },
  { category: "Text", name: "Text/Warning/Primary", cssVar: "--text-warning-primary" },
  { category: "Text", name: "Text/Warning/Secondary", cssVar: "--text-warning-secondary" },
  { category: "Text", name: "Text/Warning/Tertiary", cssVar: "--text-warning-tertiary" },
  { category: "Icon", name: "Icon/Warning/Primary", cssVar: "--icon-warning-primary" },
  { category: "Stroke", name: "Stroke/Accent3/Primary", cssVar: "--stroke-accent3-primary" },
  { category: "Stroke", name: "Stroke/Accent3/Secondary", cssVar: "--stroke-accent3-secondary" },
  { category: "Stroke", name: "Stroke/Accent3/Tertiary", cssVar: "--stroke-accent3-tertiary" },
  { category: "Text", name: "Text/Strike colors/CALL", cssVar: "--text-strike-colors-call" },
  { category: "Text", name: "Text/Strike colors/PUT", cssVar: "--text-strike-colors-put" },
  { category: "Text", name: "Text/Strike colors/FUT", cssVar: "--text-strike-colors-fut" },
];
